[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[dev]
  command = "npm run dev"
  framework = "#astro"

[[redirects]]
  from = "/*"
  to = "/.netlify/v1/functions/ssr/.netlify/build/entry.mjs"
  status = 200
  force = true

[functions]
  directory = ".netlify/v1/functions"
  node_bundler = "esbuild"

# Add headers for different asset types
[[headers]]
  for = ".netlify/build/styles/index.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/scripts/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"